### ISSUE TITLE
console errors when changing z-index of a group

### ISSUE THREAD

**Issue by mithunshanbhag** [cloudskew/cloudskew#92]
**Describe the bug**
We're observing console errors when changing the z-index of a group.

**To Reproduce**
See gif below
![zindex-group](https://user-images.githubusercontent.com/2327905/83961995-7e051d00-a8b6-11ea-83ab-bdb5ea3eddf7.gif)

**Expected behavior**
No console errors. 

**Screenshots**
If possible, add screenshots and/or screen recordings which capture the issue. These greatly help investigations.

**Errors in browser console**
```
main-es2015.0d0cf3e05f63bcc15898.js:1 ERROR DOMException: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
    at _R.moveSvgNode (https://app.cloudskew.com/main-es2015.0d0cf3e05f63bcc15898.js:1:1532485)
    at _R.sendToBack (https://app.cloudskew.com/main-es2015.0d0cf3e05f63bcc15898.js:1:1534219)
    at e.sendToBack (https://app.cloudskew.com/main-es2015.0d0cf3e05f63bcc15898.js:1:1626617)
    at YR.contextMenuItemClick (https://app.cloudskew.com/main-es2015.0d0cf3e05f63bcc15898.js:1:1787910)
    at Cw.notify (https://app.cloudskew.com/main-es2015.0d0cf3e05f63bcc15898.js:1:476251)
    at e.trigger (https://app.cloudskew.com/main-es2015.0d0cf3e05f63bcc15898.js:1:509792)
    at e.clickHandler (https://app.cloudskew.com/main-es2015.0d0cf3e05f63bcc15898.js:1:1007770)
    at a.invokeTask (https://app.cloudskew.com/polyfills-es2015.fd917e7c3ed57f282ee5.js:1:7012)
    at Object.onInvokeTask (https://app.cloudskew.com/main-es2015.0d0cf3e05f63bcc15898.js:1:91257)
    at a.invokeTask (https://app.cloudskew.com/polyfills-es2015.fd917e7c3ed57f282ee5.js:1:6933)
Ke @ main-es2015.0d0cf3e05f63bcc15898.js:1
handleError @ main-es2015.0d0cf3e05f63bcc15898.js:1
next @ main-es2015.0d0cf3e05f63bcc15898.js:1
n @ main-es2015.0d0cf3e05f63bcc15898.js:1
__tryOrUnsub @ main-es2015.0d0cf3e05f63bcc15898.js:1
next @ main-es2015.0d0cf3e05f63bcc15898.js:1
_next @ main-es2015.0d0cf3e05f63bcc15898.js:1
next @ main-es2015.0d0cf3e05f63bcc15898.js:1
next @ main-es2015.0d0cf3e05f63bcc15898.js:1
emit @ main-es2015.0d0cf3e05f63bcc15898.js:1
(anonymous) @ main-es2015.0d0cf3e05f63bcc15898.js:1
invoke @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
run @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
runOutsideAngular @ main-es2015.0d0cf3e05f63bcc15898.js:1
onHandleError @ main-es2015.0d0cf3e05f63bcc15898.js:1
handleError @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
runTask @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
invokeTask @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
y @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
k @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
```

**Additional details**
N/A

**Comment by mithunshanbhag** [comment]
Fixed checked in. Will be released to production after testing this week.

**Comment by mithunshanbhag** [comment]
Fix is now in production.
